version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      
      - restore_cache:
           keys:
             - v1-depencies-{{ checksum "requirements.txt" }}
             - v1-depencies-
      - run:
          name: "Install depencies"
          command: |
           "echo Hello, World!"
           python3 -m venv venv
           . venv/bin/activate
      - run:
          name: "Install make"
          command: |           
           make install
           
      - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
           
      - run:
          name: run lint
          command: |     
            . venv/bin/activate
            make lint
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello